#ifndef _Oedgesweep_H_
#define _Oedgesweep_H_

enum
{		
	ES_EDGE_LINK				= 1000,		
	ES_SWEEP_PROFILE			= 1001,	
	ES_SWEEP_OFFSET				= 1002,
	ES_BASIC_TAB				= 1003,
	ES_SPLINE_TYPE				= 1004,
		TYPE_LINEAR				= 0,
		TYPE_CUBIC				= 1,
		TYPE_AKIMA				= 2,
		TYPE_BSPLINE			= 3,
		TYPE_BEZIER				= 4,
	ES_SPLINE_POINTS			= 1005,
		POINTS_NONE				= 0,
		POINTS_NATURAL			= 1,
		POINTS_UNIFORM			= 2,
		POINTS_ADAPTIVE			= 3,	
	ES_SUBDIVISION				= 1006,
	ES_SPLINE_CLOSED			= 1007,
	ES_SPLINE_SUB				= 1008,
	ES_SPLINE_ANGLE				= 1009,
	ES_SWEEP_START_GROWTH		= 1010,
	ES_SWEEP_END_GROWTH			= 1011,
	ES_SWEEP_SCALE				= 1012,
	ES_SWEEP_ROTATION			= 1013,
	ES_SWEEP_BANKING			= 1014
};

#endif